<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            'Peralatan Diagnostik',
            'Alat Bantu Mobilitas',
            'Perawatan Luka',
            'P3K & Darurat',
            'Alat Terapi & Rehabilitasi',
            'Perlengkapan Proteksi Diri (APD)',
            'Kesehatan Ibu & Anak',
            'Suplemen & Vitamin',
            'Alat Perawatan Pribadi',
            'Perlengkapan Medis Habis Pakai',
        ];

        foreach ($categories as $category) {
            Category::create([
                'name' => $category,
            ]);
        }

        $products = [
            [
                'category_id' => 1,
                'name' => 'Stetoskop',
                'description' => 'Stetoskop adalah alat medis yang digunakan untuk mendengarkan suara di dalam tubuh manusia, seperti jantung dan paru-paru.<ul><li>Mendengarkan suara jantung</li><li>Mendengarkan suara paru-paru</li><li>Alat diagnostik utama untuk pemeriksaan fisik</li></ul>',
                'price' => 150000,
                'stock' => 100,
                'image' => 'stetoskop.jpg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Kursi Roda',
                'description' => 'Kursi roda adalah alat bantu mobilitas yang dirancang untuk membantu pasien yang mengalami kesulitan berjalan.<ul><li>Mobilitas untuk pasien dengan keterbatasan berjalan</li><li>Desain manual, mudah digunakan</li><li>Kenyamanan optimal untuk pengguna</li></ul>',
                'price' => 1200000,
                'stock' => 50,
                'image' => 'kursi_roda.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 1,
                'name' => 'Tensimeter Digital',
                'description' => 'Tensimeter digital adalah alat untuk mengukur tekanan darah secara praktis dan akurat.<ul><li>Mengukur tekanan darah secara digital</li><li>Memberikan hasil akurat dan cepat</li><li>Mudah digunakan di rumah</li></ul>',
                'price' => 350000,
                'stock' => 75,
                'image' => 'tensimeter_digital.jpg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Termometer Infrared',
                'description' => 'Termometer infrared adalah alat pengukur suhu tubuh tanpa kontak yang memberikan hasil cepat dan higienis.<ul><li>Mengukur suhu tubuh tanpa kontak</li><li>Hasil pengukuran cepat dan akurat</li><li>Ideal untuk pemeriksaan massal</li></ul>',
                'price' => 180000,
                'stock' => 120,
                'image' => 'termometer_infrared.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 1,
                'name' => 'Glukometer',
                'description' => 'Alat pengukur kadar gula darah yang praktis untuk penggunaan rumah.',
                'price' => 250000,
                'stock' => 80,
                'image' => 'glukometer.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 1,
                'name' => 'Oksimeter',
                'description' => 'Pengukur kadar oksigen dalam darah dan detak jantung.',
                'price' => 220000,
                'stock' => 90,
                'image' => 'oksimeter.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 2,
                'name' => 'Tongkat Bantu Jalan',
                'description' => 'Tongkat aluminium ringan dengan gagang ergonomis.',
                'price' => 120000,
                'stock' => 100,
                'image' => 'tongkat_jalan.jpg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Walker',
                'description' => 'Alat bantu jalan dengan 4 kaki untuk stabilitas maksimal.',
                'price' => 350000,
                'stock' => 60,
                'image' => 'walker.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 2,
                'name' => 'Kruk',
                'description' => 'Kruk aluminium dengan ketinggian yang dapat disesuaikan.',
                'price' => 180000,
                'stock' => 75,
                'image' => 'kruk.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 3,
                'name' => 'Perban Steril',
                'description' => 'Perban steril untuk menutupi luka dan mencegah infeksi.',
                'price' => 25000,
                'stock' => 200,
                'image' => 'perban_steril.jpg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'Antiseptik',
                'description' => 'Cairan antiseptik untuk membersihkan luka dari kuman.',
                'price' => 35000,
                'stock' => 150,
                'image' => 'antiseptik.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 3,
                'name' => 'Plester Luka',
                'description' => 'Plester untuk menutup luka kecil, tahan air.',
                'price' => 15000,
                'stock' => 300,
                'image' => 'plester_luka.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 3,
                'name' => 'Kasa Steril',
                'description' => 'Kasa steril untuk menutupi luka, tersedia dalam berbagai ukuran.',
                'price' => 20000,
                'stock' => 250,
                'image' => 'kasa_steril.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 3,
                'name' => 'Salep Anti-bakteri',
                'description' => 'Salep untuk mencegah infeksi pada luka terbuka.',
                'price' => 40000,
                'stock' => 120,
                'image' => 'salep_antibakteri.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 4,
                'name' => 'Kotak P3K',
                'description' => 'Kotak P3K lengkap untuk kebutuhan darurat rumah tangga.',
                'price' => 150000,
                'stock' => 80,
                'image' => 'kotak_p3k.jpg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Selimut Darurat',
                'description' => 'Selimut thermal untuk keadaan darurat, ringan dan praktis.',
                'price' => 60000,
                'stock' => 100,
                'image' => 'selimut_darurat.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 4,
                'name' => 'Tourniquet',
                'description' => 'Alat untuk menghentikan pendarahan berat pada situasi darurat.',
                'price' => 85000,
                'stock' => 50,
                'image' => 'tourniquet.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 4,
                'name' => 'Masker CPR',
                'description' => 'Masker untuk melakukan CPR dengan aman dan higienis.',
                'price' => 45000,
                'stock' => 70,
                'image' => 'masker_cpr.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 4,
                'name' => 'Eye Wash',
                'description' => 'Larutan pencuci mata untuk kasus darurat.',
                'price' => 30000,
                'stock' => 90,
                'image' => 'eye_wash.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 5,
                'name' => 'Bola Terapi Genggam',
                'description' => 'Bola untuk terapi dan rehabilitasi tangan.',
                'price' => 50000,
                'stock' => 120,
                'image' => 'bola_terapi.jpg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'TENS Unit',
                'description' => 'Alat stimulasi saraf transkutan elektrik untuk terapi nyeri.',
                'price' => 450000,
                'stock' => 40,
                'image' => 'tens_unit.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 5,
                'name' => 'Hot & Cold Pack',
                'description' => 'Kompres panas dan dingin untuk terapi cedera.',
                'price' => 75000,
                'stock' => 100,
                'image' => 'hot_cold_pack.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 5,
                'name' => 'Alat Terapi Pernafasan',
                'description' => 'Alat latihan pernafasan untuk rehabilitasi paru-paru.',
                'price' => 180000,
                'stock' => 60,
                'image' => 'terapi_pernafasan.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 5,
                'name' => 'Karet Resistance Band',
                'description' => 'Karet elastis untuk terapi dan latihan rehabilitasi fisik.',
                'price' => 95000,
                'stock' => 150,
                'image' => 'resistance_band.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 6,
                'name' => 'Masker N95',
                'description' => 'Masker medis dengan perlindungan tingkat tinggi.',
                'price' => 25000,
                'stock' => 500,
                'image' => 'masker_n95.jpg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => 6,
                'name' => 'Face Shield',
                'description' => 'Pelindung wajah transparan untuk perlindungan lengkap.',
                'price' => 45000,
                'stock' => 300,
                'image' => 'face_shield.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 6,
                'name' => 'Sarung Tangan Latex',
                'description' => 'Sarung tangan sekali pakai untuk perlindungan dari kontaminasi.',
                'price' => 85000,
                'stock' => 400,
                'image' => 'sarung_tangan_latex.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 6,
                'name' => 'APD Set Lengkap',
                'description' => 'Set lengkap alat pelindung diri untuk tenaga medis.',
                'price' => 350000,
                'stock' => 100,
                'image' => 'apd_set.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 6,
                'name' => 'Kacamata Pelindung',
                'description' => 'Kacamata safety untuk melindungi mata dari percikan.',
                'price' => 65000,
                'stock' => 150,
                'image' => 'kacamata_pelindung.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 7,
                'name' => 'Pompa ASI',
                'description' => 'Pompa ASI elektrik dengan teknologi dual pump.',
                'price' => 650000,
                'stock' => 50,
                'image' => 'pompa_asi.jpg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => 7,
                'name' => 'Botol Susu Anti Kolik',
                'description' => 'Botol susu khusus untuk mencegah kolik pada bayi.',
                'price' => 120000,
                'stock' => 100,
                'image' => 'botol_susu.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 7,
                'name' => 'Termometer Bayi',
                'description' => 'Termometer digital khusus untuk bayi dengan ujung lembut.',
                'price' => 85000,
                'stock' => 80,
                'image' => 'termometer_bayi.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 7,
                'name' => 'Monitor Bayi',
                'description' => 'Alat pemantau kondisi dan aktivitas bayi secara real-time.',
                'price' => 750000,
                'stock' => 40,
                'image' => 'monitor_bayi.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 7,
                'name' => 'Bantal Menyusui',
                'description' => 'Bantal ergonomis untuk kenyamanan menyusui.',
                'price' => 180000,
                'stock' => 60,
                'image' => 'bantal_menyusui.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 8,
                'name' => 'Vitamin C 1000mg',
                'description' => 'Suplemen vitamin C dosis tinggi untuk daya tahan tubuh.',
                'price' => 120000,
                'stock' => 200,
                'image' => 'vitamin_c.jpg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => 8,
                'name' => 'Multivitamin Harian',
                'description' => 'Suplemen multivitamin lengkap untuk kebutuhan harian.',
                'price' => 150000,
                'stock' => 180,
                'image' => 'multivitamin.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 8,
                'name' => 'Omega 3',
                'description' => 'Suplemen asam lemak omega 3 untuk kesehatan jantung dan otak.',
                'price' => 180000,
                'stock' => 150,
                'image' => 'omega3.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 8,
                'name' => 'Kalsium + Vitamin D',
                'description' => 'Suplemen untuk kesehatan tulang dan gigi.',
                'price' => 135000,
                'stock' => 160,
                'image' => 'kalsium_vit_d.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 8,
                'name' => 'Zinc',
                'description' => 'Suplemen zinc untuk meningkatkan imunitas tubuh.',
                'price' => 95000,
                'stock' => 190,
                'image' => 'zinc.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 9,
                'name' => 'Sikat Gigi Elektrik',
                'description' => 'Sikat gigi elektrik dengan teknologi ultrasonic.',
                'price' => 350000,
                'stock' => 70,
                'image' => 'sikat_gigi_elektrik.jpg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => 9,
                'name' => 'Alat Pemotong Kuku',
                'description' => 'Set alat manicure dan pedicure lengkap.',
                'price' => 85000,
                'stock' => 100,
                'image' => 'pemotong_kuku.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 9,
                'name' => 'Ear Cleaner Kit',
                'description' => 'Alat pembersih telinga dengan kamera endoskopi.',
                'price' => 165000,
                'stock' => 60,
                'image' => 'ear_cleaner.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 9,
                'name' => 'Alat Cukur Elektrik',
                'description' => 'Alat cukur elektrik dengan fitur wet & dry.',
                'price' => 250000,
                'stock' => 80,
                'image' => 'alat_cukur.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 9,
                'name' => 'Foot Spa',
                'description' => 'Alat perawatan kaki dengan fitur pijat dan pemanasan.',
                'price' => 320000,
                'stock' => 50,
                'image' => 'foot_spa.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 10,
                'name' => 'Jarum Suntik',
                'description' => 'Jarum suntik steril sekali pakai berbagai ukuran.',
                'price' => 5000,
                'stock' => 1000,
                'image' => 'jarum_suntik.jpg',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => 10,
                'name' => 'Kapas Medis',
                'description' => 'Kapas steril untuk penggunaan medis.',
                'price' => 15000,
                'stock' => 500,
                'image' => 'kapas_medis.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 10,
                'name' => 'Test Pack Kehamilan',
                'description' => 'Alat tes kehamilan akurat dengan hasil cepat.',
                'price' => 18000,
                'stock' => 300,
                'image' => 'test_pack.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 10,
                'name' => 'Kantong Urin',
                'description' => 'Kantong penampungan urin medis dengan kateter.',
                'price' => 25000,
                'stock' => 200,
                'image' => 'kantong_urin.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => 10,
                'name' => 'Masker Bedah',
                'description' => 'Masker bedah sekali pakai untuk penggunaan medis.',
                'price' => 35000,
                'stock' => 800,
                'image' => 'masker_bedah.jpg',
                'is_active' => true,
                'is_featured' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
